### ISSUE TITLE
파이토치 설치 오류 관련하여 문의 드립니다.

### ISSUE THREAD

**Issue by Qualia-017** [keon/3-min-pytorch#20]
pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.3.1+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.3.1+cpu 

안녕하세요. 책 재미있게 읽고, 실습을 위해 설치하려는데, 계속 설치가 안되네요. 처음에는 파이썬 3.8 이어서 안되나 하고 3.7.3 으로 책에 나온것과 같은 버전으로 받아서 재설치 했습니다. 저 위에 숫자도 1.3.0 과 0.4.1 모두 넣어서 해보았으나 계속해서 에러가 발생합니다. 어떻게 설치해야 하나요?
현재 운영체제는 윈도우 10 64 비트 입니다. 감사합니다.

**Comment by keon** [comment]
중복 #21
