### ISSUE TITLE
파이토치 설치관련..

### ISSUE THREAD

**Issue by Qualia-017** [keon/3-min-pytorch#21]
test 환경 만들어 파이토치, 토치비전 전부 설치하였는데, 코드로 체크하면
토치비전이 없다고 나오네요. pip list 로는 설치된것으로 나오는데 어디가 문제일까요?

![1](https://user-images.githubusercontent.com/59431582/71709046-65d92f80-2e38-11ea-9163-b11b74e7ee0a.JPG)
![2](https://user-images.githubusercontent.com/59431582/71709047-65d92f80-2e38-11ea-93cf-767307399e59.JPG)

**Comment by keon** [comment]
안녕하세요 
혹시 sudo 키워드로 설치하셨나요?
설치된 pip과 사용하는 pip경로가 다른것 같습니다.

which pip
으로 어느 pip을 사용하고있는지 확인해주세요.

**Comment by Qualia-017** [comment]
(test1env) d:\test1\test1env\Scripts>pip --version
pip 19.3.1 from d:\test1\test1env\lib\site-packages\pip (python 3.7)

(test1env) d:\test1\test1env\Scripts> 

이렇게 나옵니다. sudo 키워드는 뭔지 모릅니다. 사실 파이썬 자체도 써보지 않은 완전 초보자라,
유튜브와 선생님의 책을 보면서 개념 파악부터 하고 있습니다. 답변에 감사드립니다.

**Comment by keon** [comment]
아 윈도우환경이시군요. 
아나콘다로 한번 해보시겠어요?
아나콘다 설치: https://enjoysomething.tistory.com/40
아나콘다 설치후 파이토치 설치: https://dreamgonfly.github.io/2018/01/30/conda-pytorch.html
